DELETE http://localhost:3000/api/persons/10
###
POST  http://localhost:3001/api/persons
content-type: application/json

{
    "name": "e",
    "number": "41870884"
}

###
GET http://localhost:3000/api/persons

####
PUT http://localhost:3001/api/persons/66faf4576c8b700aa6318c9a
content-type: application/json

{
    "name": "Juan Diego Garzon Becerra",
    "number": "41870884"
}